[tox]
envlist = ruff, ty
isolated_build = true

[testenv:ruff]
deps =
    ruff==0.15.22
changedir = {toxinidir}
commands =
    ruff check .

[testenv:ty]
deps =
    ty>=0.1.0
changedir = {toxinidir}
commands =
    ty check .
